/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../components/about/About.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Files: typeof import('./../components/files/files.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Note: typeof import('./../components/notes/note.vue')['default']
    Notes: typeof import('./../components/notes/notes.vue')['default']
  }
}
