/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Files: typeof import('./../components/files/files.vue')['default']
  }
}
